import logging
from collections import defaultdict
from app.core.supabase import supabase
from app.models.registration import RegistrationInput
from app.services.email_service import send_combined_qr_email, send_info_emails
from app.services.qr_service import generate_qr_image

logger = logging.getLogger(__name__)


def check_country_quota(country: str, new_member_count: int):
    """Check if adding new members would exceed the country's quota.

    Each country has a max member limit set in the country_quotas table.
    Only counts members from PAID registrations (not pending/failed).
    If no quota row exists for a country, registration is unlimited.
    """
    quota_result = supabase.table("country_quotas").select("max_members").eq("country_code", country).execute()

    if not quota_result.data:
        return  # no quota row = unlimited registrations for this country

    max_allowed = quota_result.data[0]["max_members"]

    # Count members from paid registrations for this country
    # Joins registrations → payments where payment status = 'paid', sums member_count
    result = (
        supabase.table("registrations")
        .select("member_count, payments!inner(status)")
        .eq("country", country)
        .eq("payments.status", "paid")
        .execute()
    )
    current_count = sum(row["member_count"] for row in result.data) if result.data else 0
    if current_count + new_member_count > max_allowed:
        raise ValueError(
            "Jay Swaminarayan, We're sorry, all spots for your country have been filled. "
            "Registration is now closed. Please contact your reglional Leader for further information."
        )


def create_registration(data: RegistrationInput) -> dict:
    """Save registration + members to DB. Returns data needed for background QR/email processing.

    Flow:
      1. Check country quota
      2. Insert into 'registrations' table (seq auto-generated by DB to avoid race conditions)
      3. Read back the DB-generated seq, build reference like "HP-2026-00042"
      4. Insert each member into 'members' table
      5. If any member insert fails, delete the registration (CASCADE cleans up members)
      6. Return data dict for the background task to generate QR codes and send emails
    """
    check_country_quota(data.country, len(data.members))

    # seq is BIGSERIAL in DB — auto-increments atomically, no race condition
    # We insert WITHOUT seq, then read it back from the response
    reg_result = supabase.table("registrations").insert({
        "country": data.country,
        "karyakarta": data.karyakarta,
        "member_count": len(data.members),
        "terms_accepted": data.terms_accepted,
    }).execute()

    registration_id = reg_result.data[0]["id"]
    seq = reg_result.data[0]["seq"]  # DB-generated sequence number
    reference = f"HP-2026-{seq:05d}"  # e.g. "HP-2026-00042"

    # Update the row with the formatted reference (built from DB-generated seq)
    supabase.table("registrations").update({"reference": reference}).eq("id", registration_id).execute()

    logger.info(f"Registration created: {reference} for country {data.country}")

    # Insert each member with a ticket number like "HP-2026-00042-M1", "HP-2026-00042-M2"
    members_data = []
    for index, member in enumerate(data.members, start=1):
        ticket_number = f"{reference}-M{index}"

        member_data = {
            "registration_id": registration_id,
            "ticket_number": ticket_number,
            "first_name": member.first_name,
            "middle_name": member.middle_name,
            "last_name": member.last_name,
            "gender": member.gender.value,  # Enum → string ("male"/"female")
            "dob": str(member.dob),
            "email": member.email,
            "phone": member.phone,
            "checked_in": False,
        }

        try:
            supabase.table("members").insert(member_data).execute()
            members_data.append(member_data)
        except Exception:
            # Rollback: delete the registration row.
            # The DB has ON DELETE CASCADE, so all already-inserted members are cleaned up too.
            logger.exception(f"Failed to insert member {index} for {reference}, rolling back")
            supabase.table("registrations").delete().eq("id", registration_id).execute()
            raise ValueError("Registration failed. Please try again.")

    logger.info(f"Inserted {len(members_data)} members for {reference}")

    return {
        "registration_id": registration_id,
        "reference": reference,
        "member_count": len(data.members),
        "members_data": members_data,
    }


def process_qr_and_emails(registration_id: str, members_data: list, primary_email: str, reference: str = ""):
    """Background task: generate QR codes, upload to storage, update DB, send emails.

    Runs AFTER the API has already responded to the user (via FastAPI BackgroundTasks).
    This keeps the API response fast — user doesn't wait for QR generation or email delivery.

    Email distribution logic:
      - Primary email (the main registering member) receives ALL members' QR codes
        in a single combined email, so they have everyone's check-in QR.
      - Other members who have their own email receive ONLY their own QR code.
      - Travel Guide and Social (WhatsApp/Instagram/Telegram) emails are sent
        once per unique email address (no duplicates).

    Example with 3 members: M1=john@, M2=no email, M3=bob@
      john@ receives: 1 email with M1+M2+M3 QR codes, Travel Guide, Social = 3 emails
      bob@  receives: 1 email with M3 QR code, Travel Guide, Social        = 3 emails
      Total: 6 emails
    """

    # ── Step 1: Generate QR code for every member ──
    # Each QR encodes the ticket number (e.g. "HP-2026-00042-M1").
    # The PNG is uploaded to Supabase Storage, and the public URL is saved in the members table.
    all_members_qr = []
    unique_emails = set()

    for member_data in members_data:
        ticket_number = member_data["ticket_number"]

        # QR generation can fail (e.g. storage down) — we catch it and continue
        # so that emails are still sent (with a fallback message instead of QR image)
        qr_bytes = None
        try:
            qr_bytes, qr_url = generate_qr_image(ticket_number)
            supabase.table("members").update({"qr_url": qr_url}).eq("ticket_number", ticket_number).execute()
        except Exception:
            logger.exception(f"QR generation/upload failed for {ticket_number}")

        member_name = f"{member_data['first_name']} {member_data['last_name']}"
        member_email = member_data.get("email")

        all_members_qr.append({
            "member_name": member_name,
            "ticket_number": ticket_number,
            "qr_bytes": qr_bytes,
            "email": member_email,
        })

        # Resolve email: use member's own email, or fall back to primary
        unique_emails.add(member_email or primary_email)

    # ── Step 2: Send combined QR email to primary (main registering member) ──
    # Primary always gets ALL QR codes so they can check in the whole group
    try:
        send_combined_qr_email(primary_email, all_members_qr, reference=reference)
    except Exception:
        logger.exception("Combined QR email failed for primary contact")

    # ── Step 3: Send individual QR email to other members who have their own email ──
    # Skip primary (they already got all QR codes above)
    for item in all_members_qr:
        if item["email"] and item["email"] != primary_email:
            try:
                send_combined_qr_email(item["email"], [item], reference=reference)
            except Exception:
                logger.exception("QR email failed for a member")

    # ── Step 4: Send info emails (Travel Guide + Social) once per unique email ──
    # Deduplicated: even if primary has 3 members proxied to them,
    # they only get 1 Travel Guide email and 1 Social email
    for email_address in unique_emails:
        try:
            send_info_emails(email_address)
        except Exception:
            logger.exception("Info emails failed for a recipient")
